---
development:
  magento:
    url: http://www.gemgento.com
    username: gemgento
    api_key: ''
    debug: false
  layout: gemgento
beta:
  magento:
    url: http://www.gemgento.com
    username: gemgento
    api_key: ''
  layout: gemgento
production:
  magento:
    url: http://www.gemgento.com
    username: gemgento
    api_key: ''
    ip_whitelist: 127.0.0.1
  layout: gemgento
  require_ssl: true
